CorrelAid/correlaid_website

- src/lib/components/Card.svelte
- src/lib/components/Partner.svelte
- src/lib/components/Person.svelte
- src/lib/components/Timeline.svelte
- src/lib/layout/Footer.svelte
- src/lib/layout/MobileDrawer.svelte
- src/routes/[[locale=locale]]/blog/+page.svelte
- width adjustments for the text for Person and Partner components
- Fixed side drawer availability media query mismatch
- Fixed create local chapter z-level conflict with side drawer
- Fixed podcast card headline line-clamp issues
- Fixed Instagram link
- added left/right padding to blog post previews
> added some design adjustments

- README.md
> updated readme with qa info

- src/lib/layout/HeaderBottomNav.svelte
> aligned text for header nav drop down menues

- src/lib/components/Awards.svelte
- src/routes/[[locale=locale]]/[about=about]/+page.js
- src/routes/[[locale=locale]]/[about=about]/+page.svelte
Added Awards to About us. Test design for desktop and mobile.
Issue: https://github.com/CorrelAid/correlaid_website/issues/153
> 153 add awards section to about us

- src/routes/[[locale=locale]]/[using_data=using_data]/[consulting=consulting]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[consulting=consulting]/queries.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/queries.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/queries.js
- src/routes/[[locale=locale]]/podcast/+page.server.js
- src/routes/[[locale=locale]]/podcast/queries.js
> explicit query files for podcast and using_data routes

- src/lib/components/Hero.spec.js
- src/lib/components/Hero.svelte
> adjusted correlaidx logo z-index and added simple hero test

- src/lib/components/Blog_Card.svelte
- src/lib/js/helpers.js
- src/routes/[[locale=locale]]/+page.svelte
- src/routes/[[locale=locale]]/blog/+page.svelte
- src/routes/[[locale=locale]]/blog/[slug]/queries.js
- src/routes/[[locale=locale]]/podcast/+page.svelte
- tailwind.config.cjs
@jstet reapplying your PR after cleaning up some branch misalighnment.
> 257 dont link to blog post in nonexisting language version

- .gitignore
- README.md
- package-lock.json
- package.json
- playwright.config.js
- tests/nav-menu.spec.js
> added playwright and first tests including different viewports

- src/lib/components/Avatar.svelte
- src/lib/components/Awards.svelte
- src/lib/components/Person.svelte
- src/lib/js/parse_cms.js
- src/lib/js/parse_cms_models/index.js
- src/lib/js/parse_cms_models/people.js
- src/routes/+layout.svelte
- src/routes/[[locale=locale]]/[about=about]/+page.server.js
- src/routes/[[locale=locale]]/[about=about]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/[partners=partners]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/[values=values]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/team/+page.svelte
- src/routes/[[locale=locale]]/[using_data=using_data]/[consulting=consulting]/+page.svelte
- src/routes/[[locale=locale]]/blog/[slug]/+page.svelte
- src/routes/[[locale=locale]]/community/correlaidx/[slug]/+page.svelte
> refactored parsing of different types of people for the entire site

- src/lib/components/WorkshopCard.svelte
- src/lib/js/parse_cms_models/cards.js
- src/lib/js/parse_cms_models/index.js
- src/routes/[[locale=locale]]/[education=education]/[resources=resources]/+page.svelte
> explicit parsing of workshop cards and card parsing as submodule

- src/lib/components/Blog_Card.svelte
- src/lib/js/parse_cms_models/cards.js
- src/routes/[[locale=locale]]/podcast/queries.js
- src/routes/[[locale=locale]]/queries.js
> added podcast image

- src/lib/data/translations.js
- two typo fixes 
- Projects -> Data4Good Projects
> Small fixes to navbar titles

- src/routes/+layout.svelte
adds Data4Good to page title 
closes #340 (despite branch name... sorry for that)
> Longer page title

- README.md
- src/lib/js/parse_cms.js
- src/routes/+layout.svelte
> added env var configuration for CMS parsing errors

- src/lib/components/Blog_Card.spec.js
- src/lib/components/Hero.spec.js
- src/lib/components/Partner.spec.js
- src/lib/js/helpers.js
- src/lib/js/parse_cms.js
- src/routes/+layout.server.js
- src/routes/+layout.svelte
- src/routes/[[locale=locale]]/[events=events]/[slug]/+page.server.js
- src/routes/[[locale=locale]]/[events=events]/[slug]/+page.svelte
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/+page.svelte
- src/routes/[[locale=locale]]/blog/[slug]/+page.server.js
- src/routes/[[locale=locale]]/blog/[slug]/+page.svelte
- src/routes/[[locale=locale]]/community/correlaidx/[slug]/+page.server.js
- src/routes/[[locale=locale]]/community/correlaidx/[slug]/+page.svelte
Moved all parsing to server side to ensure that it happens at build time for a static page
> Added explicit parsing for lc pages, event pages and blog posts

- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/+page.svelte
> use Html component for organization descriptions

- playwright.config.js
- src/routes/[[locale=locale]]/community/correlaidx/+page.svelte
- src/routes/[[locale=locale]]/community/correlaidx/[slug]/+page.server.js
- svelte.config.js
- tests/all-nav-links.spec.js
- tests/lc-pages.spec.js
> added lower case url paths for lc cities

- package.json
- src/lib/js/helpers.js
- src/routes/[[locale=locale]]/community/correlaidx/+page.svelte
- tests/lc-pages.spec.js
> fixed lc links outside of correlaidx route und unified link generation

- src/lib/components/Links.svelte
- src/lib/layout/Footer.svelte
implements #395 
implements #396
> added target blank to footer social media links in footer and for people links

- src/lib/components/Blog_Card.svelte
- src/lib/components/Link_Button.svelte
- src/lib/components/ProjectLinks.svelte
- src/routes/[[locale=locale]]/[events=events]/[slug]/+page.svelte
- vercel.json
> adjusted vercel redirects for lower case city names

- src/lib/components/Events_Card.svelte
- src/lib/js/helpers.js
- src/lib/js/parse_cms_models/cards.js
- src/routes/[[locale=locale]]/[events=events]/+page.svelte
- src/routes/[[locale=locale]]/[events=events]/queries.js
> Added future and past events to event page

- README.md
> updated readme with "how to contribute"

- vercel.json
see discussion in #334
follow up PR.
> add more redirects after analysis of google search console

- src/lib/components/Blog_Card.svelte
- src/lib/components/Events_Card.svelte
- src/lib/components/ProjectsCard.svelte
- src/lib/components/Quote_Carousel.svelte
- src/lib/components/WorkshopCard.svelte
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/+page.svelte
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/+page.svelte
- tailwind.config.cjs
- tests/lc-pages.spec.js
Moves parsing related to #466 server side. Should be merged once the underlying directus issue is resolved, otherwise the production build will fail anyways.
Edit: There was no problem in directus, but a pre-existing Bug in the code triggered the issue. Priviously the case simply did not come up.
fixes #466
> server side parsing of project overview

- src/routes/[[locale=locale]]/+page.server.js
- src/routes/[[locale=locale]]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/+page.server.js
- src/routes/[[locale=locale]]/[about=about]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/[partners=partners]/+page.server.js
- src/routes/[[locale=locale]]/[about=about]/[partners=partners]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/[values=values]/+page.server.js
- src/routes/[[locale=locale]]/[about=about]/[values=values]/+page.svelte
- src/routes/[[locale=locale]]/[about=about]/team/+page.server.js
- src/routes/[[locale=locale]]/[about=about]/team/+page.svelte
- src/routes/[[locale=locale]]/[education=education]/[resources=resources]/+page.server.js
- src/routes/[[locale=locale]]/[education=education]/[resources=resources]/+page.svelte
- src/routes/[[locale=locale]]/[events=events]/+page.server.js
- src/routes/[[locale=locale]]/[events=events]/+page.svelte
- src/routes/[[locale=locale]]/[using_data=using_data]/[consulting=consulting]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[consulting=consulting]/+page.svelte
- src/routes/[[locale=locale]]/blog/+page.server.js
- src/routes/[[locale=locale]]/blog/+page.svelte
- src/routes/[[locale=locale]]/podcast/+page.server.js
- src/routes/[[locale=locale]]/podcast/+page.svelte
> moved remaining parsing to server side

- README.md
- src/lib/js/directus_fetch.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/[slug]/queries.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/queries.js
implemented it for project related queries. Hardcoded filters for published projects
closes #473
It only makes sense to merge this PR once the environment variables are configured for production. @jstet let me know when this is the case or feel free to merge this PR then if everything else checks out.
> added authorized directus fetch method

- README.md
Tiny formatting fix in readme.
> contribution information regarding token

- src/lib/components/Events_Card.svelte
- src/lib/js/parse_cms_models/cards.js
also  and aligned local chapter naming for event and project cards
> explcicitly parse local chapter names for events

- src/lib/components/Events_Card.svelte
fixes an issue overlooked in #490
> Project Card and Event Card code alignment

- src/lib/components/ProjectsCard.svelte
- src/lib/data/translations.js
- src/lib/js/parse_cms_models/cards.js
- src/lib/js/parse_cms_models/cards.spec.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[projects=projects]/queries.js
- svelte.config.js
> added internal projects with correlaid logo

- src/lib/js/parse_cms.js
> fixed missing lc emails

- src/lib/components/Job_Card.svelte
- src/lib/js/entries.js
- src/routes/[[locale=locale]]/[events=events]/+page.svelte
- src/routes/[[locale=locale]]/jobs/+page.svelte
- src/routes/[[locale=locale]]/jobs/[slug]/queries.js
> split current and past (deadline) job annoucements

- src/lib/js/helpers.js
small fix to add Werkstudi in the job card.
> Werkstudi in job card

- src/lib/js/directus_fetch.js
- src/lib/js/parse_cms_models/cards.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[project_database=project_database]/+page.server.js
- src/routes/[[locale=locale]]/[using_data=using_data]/[project_database=project_database]/[slug]/+page.server.js
- src/routes/[[locale=locale]]/[volunteering=volunteering]/correlaidx/[slug]/+page.server.js
- svelte.config.js
> Directus fetch condition

- .gitignore
- package-lock.json
- package.json
- vite.config.js
fixes styling issues that prevent action from completing
add svelte-testing
> Fix build after update to svelte 4
